"""empty message

Revision ID: 09f51a71e79f
Revises: c2a9b4a83b0a
Create Date: 2018-12-14 09:45:51.586833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f51a71e79f'
down_revision = 'c2a9b4a83b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    op.drop_column('user', 'real_avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('real_avatar', sa.VARCHAR(length=128), nullable=True))
    op.add_column('post', sa.Column('language', sa.VARCHAR(length=5), nullable=True))
    # ### end Alembic commands ###
