"""empty message

Revision ID: c2a9b4a83b0a
Revises: b5f0cff07524
Create Date: 2018-12-13 21:18:35.726162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a9b4a83b0a'
down_revision = 'b5f0cff07524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('real_avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'real_avatar')
    # ### end Alembic commands ###
